# frozen_string_literal: true

require "rake/testtask"

Rake::TestTask.new(:test) do |t|
  t.libs << "test"
  t.libs << "lib"
  t.test_files = FileList["test/test_*.rb"]
  t.warning = false
end

desc "Run the gem against a real `graphmind serve` (cross-checks the RFC 6455 client)"
task :live do
  ruby "-Ilib -Itest test/live_server_check.rb"
end

task default: :test
