/**
 * The payload shrink (src/shrink.ts): the conformance fixture reproduced byte
 * for byte, plus the TypeScript-specific behaviour the fixture cannot carry
 * (unserializable values, the byte counter, idempotence under random input).
 *
 * test/fixtures/shrink.json version 1 was generated from the server
 * implementation this module was moved out of (packages/cli/src/storage.ts at
 * 3ea2fe1), so reproducing it proved the move kept behaviour. Version 2
 * (shrink v2: the key cap and the skeleton tier) is regenerated by
 * test/fixtures/gen-shrink.mjs against the built package; it keeps every
 * version-1 case and records whether its output changed. The Python and Ruby
 * ports run the same fixture.
 */
import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import fc from 'fast-check';
import { describe, expect, it } from 'vitest';
import {
  MAX_PAYLOAD_BYTES,
  isTruncatedPayload,
  serializePayload,
  type TruncatedPayload,
} from '../src/index.js';
import {
  MAX_SHRINK_DEPTH,
  MAX_SHRINK_KEYS,
  MAX_TRIM_FIELDS,
  PREVIEW_CHARS,
  SKELETON_CHARS,
  SKELETON_MIN_CHARS,
  TRUNCATION_SUFFIX,
  countUtf8Bytes,
  skeletonPlan,
  utf8ByteLength,
  type SkeletonPlan,
} from '../src/shrink.js';
import { EVENT_TYPES } from '../src/index.js';

interface FixtureCase {
  name: string;
  note: string;
  since: 1 | 2;
  v1?: string;
  type?: string;
  maxBytes?: number;
  input: unknown;
  expected:
    | { truncated: boolean; json: string }
    | { truncated: boolean; jsonBytes: number; jsonSha256: string; jsonHead: string; jsonTail: string };
}

interface Fixture {
  version: number;
  constants: Record<string, number | string>;
  skeletonPlans: Record<string, unknown>;
  cases: FixtureCase[];
}

const fixture = JSON.parse(
  readFileSync(new URL('./fixtures/shrink.json', import.meta.url), 'utf8'),
) as Fixture;

/** An own data property, even for the key "__proto__" (see the fixture's generator note). */
function setOwn(target: Record<string, unknown>, key: string, value: unknown): void {
  Object.defineProperty(target, key, { value, writable: true, enumerable: true, configurable: true });
}

/**
 * The fixture's generator notation: {"$repeat": [unit, count]}, {"$array":
 * [item, count]}, {"$concat": [part, ...]}, {"$keys": [prefix, count, item]}
 * and {"$merge": [object, ...]}. Same as test/fixtures/gen-shrink.mjs.
 */
function expand(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(expand);
  if (value !== null && typeof value === 'object') {
    const record = value as Record<string, unknown>;
    const keys = Object.keys(record);
    const only = keys.length === 1 ? keys[0] : undefined;
    if (only === '$repeat') {
      const [unit, count] = record['$repeat'] as [string, number];
      return unit.repeat(count);
    }
    if (only === '$array') {
      const [item, count] = record['$array'] as [unknown, number];
      return Array.from({ length: count }, () => expand(item));
    }
    if (only === '$concat') return (record['$concat'] as unknown[]).map(expand).join('');
    if (only === '$keys') {
      const [prefix, count, item] = record['$keys'] as [string, number, unknown];
      const out: Record<string, unknown> = {};
      for (let i = 0; i < count; i += 1) setOwn(out, `${prefix}${i}`, expand(item));
      return out;
    }
    if (only === '$merge') {
      const out: Record<string, unknown> = {};
      for (const part of record['$merge'] as unknown[]) {
        const expanded = expand(part) as Record<string, unknown>;
        for (const key of Object.keys(expanded)) setOwn(out, key, expanded[key]);
      }
      return out;
    }
    const out: Record<string, unknown> = {};
    for (const key of keys) setOwn(out, key, expand(record[key]));
    return out;
  }
  return value;
}

function planToJson(plan: SkeletonPlan): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  for (const [key, sub] of plan.keys) out[key] = sub === null || sub === 'optional' ? sub : planToJson(sub);
  return out;
}

describe('shrink.json conformance fixture', () => {
  it('pins the constants the ports need', () => {
    expect(fixture.version).toBe(2);
    expect(fixture.constants).toEqual({
      MAX_PAYLOAD_BYTES,
      PREVIEW_CHARS,
      MAX_SHRINK_DEPTH,
      TRUNCATION_SUFFIX,
      MAX_SHRINK_KEYS,
      MAX_TRIM_FIELDS,
      SKELETON_CHARS,
      SKELETON_MIN_CHARS,
    });
    expect(MAX_PAYLOAD_BYTES).toBe(512 * 1024);
    expect(MAX_SHRINK_KEYS).toBe(256);
    expect(MAX_TRIM_FIELDS).toBe(4096);
    expect(SKELETON_CHARS).toBe(256);
    expect(SKELETON_MIN_CHARS).toBe(32);
  });

  it('pins the skeleton plans the ports use, derived from the event schemas', () => {
    const plans: Record<string, unknown> = {};
    for (const type of EVENT_TYPES) {
      const plan = skeletonPlan(type);
      if (plan !== undefined) plans[type] = planToJson(plan);
    }
    expect(Object.keys(plans).sort()).toEqual([...EVENT_TYPES].sort());
    expect(fixture.skeletonPlans).toEqual(plans);
    expect(plans['node.error']).toEqual({
      nodeId: null,
      instanceId: 'optional',
      error: { name: null, message: null, stack: 'optional' },
      heldMs: 'optional',
    });
    expect(plans['run.started']).toEqual({ app: null, sdk: { name: null, version: null }, meta: 'optional' });
  });

  it('keeps every version-1 case, unchanged unless it says why', () => {
    const v1 = fixture.cases.filter((c) => c.since === 1);
    expect(v1).toHaveLength(25);
    for (const c of v1) expect(typeof c.v1, c.name).toBe('string');
  });

  it('covers every case the contract names', () => {
    const names = fixture.cases.map((c) => c.name);
    for (const required of [
      'under-budget-object',
      'huge-ascii-string-field',
      'huge-cjk-string-field-mixed-units',
      'astral-string-field-split-surrogate',
      'huge-array-field',
      'huge-nested-object-field',
      'several-large-fields-biggest-first',
      'node-error-required-string',
      'bare-huge-string-payload',
      'non-object-huge-array-payload',
      'depth-beyond-max-shrink-depth',
      'keyed-records-node-finished',
      'many-medium-fields-node-finished',
      'typed-array-2m-keys-node-finished',
      'node-error-1mb-message-10k-extra-keys',
      'run-started-huge-meta',
      'huge-loose-field-before-required',
      'astral-at-256-cut-skeleton-no-preview',
      'astral-at-2000-cut-field-trim',
      'cjk-at-256-cut-skeleton-multibyte-preview',
      'escape-heavy-skeleton-min-chars',
      'unknown-type-whole-marker',
    ]) {
      expect(names).toContain(required);
    }
    expect(new Set(names).size).toBe(names.length);
  });

  for (const testCase of fixture.cases) {
    it(`reproduces "${testCase.name}" byte for byte`, () => {
      const input = expand(testCase.input);
      const result =
        testCase.type === undefined && testCase.maxBytes === undefined
          ? serializePayload(input)
          : serializePayload(input, testCase.maxBytes ?? MAX_PAYLOAD_BYTES, testCase.type);
      expect(result.truncated).toBe(testCase.expected.truncated);
      // The JSON text and the effective payload always agree.
      expect(JSON.stringify(result.payload)).toBe(result.json);
      if ('json' in testCase.expected) {
        // Compared as booleans so a mismatch does not print megabytes.
        const same = result.json === testCase.expected.json;
        if (!same) {
          let at = 0;
          while (at < result.json.length && result.json[at] === testCase.expected.json[at]) at += 1;
          expect.fail(
            `json differs at unit ${at}: got ${JSON.stringify(result.json.slice(at, at + 80))}, ` +
              `want ${JSON.stringify(testCase.expected.json.slice(at, at + 80))}`,
          );
        }
      } else {
        expect(utf8ByteLength(result.json)).toBe(testCase.expected.jsonBytes);
        expect(result.json.slice(0, 160)).toBe(testCase.expected.jsonHead);
        expect(result.json.slice(-160)).toBe(testCase.expected.jsonTail);
        expect(createHash('sha256').update(result.json, 'utf8').digest('hex')).toBe(testCase.expected.jsonSha256);
      }
      if (result.truncated) {
        expect(isTruncatedPayload(result.payload)).toBe(true);
      } else {
        // Untouched means the very same value back, not a copy.
        expect(result.payload).toBe(input);
      }
    });
  }
});

describe('utf8ByteLength (chunked TextEncoder) and countUtf8Bytes (no-TextEncoder fallback)', () => {
  const encoder = new TextEncoder();
  const both = (text: string): [number, number] => [utf8ByteLength(text), countUtf8Bytes(text)];

  it('count like a UTF-8 encoder on the edge cases', () => {
    for (const text of [
      '',
      'a',
      '\u007f',
      '\u0080',
      '\u07ff',
      '\u0800',
      '\uffff',
      'é中😀',
      '\ud83d', // lone high surrogate at the end -> U+FFFD, 3 bytes
      '\ude00', // lone low surrogate -> 3 bytes
      '\ud83dx', // high surrogate followed by a non-surrogate
      '\ude00\ud83d', // reversed pair: two lone halves
      '\ud83d\ud83d\ude00', // lone high, then a real pair
    ]) {
      const want = Buffer.byteLength(text);
      expect(encoder.encode(text).length).toBe(want);
      expect(both(text), JSON.stringify(text)).toEqual([want, want]);
    }
  });

  it('are exact when a surrogate pair or a lone half straddles the 65,536-unit chunk boundary', () => {
    const CHUNK = 65_536;
    for (let offset = CHUNK - 3; offset <= CHUNK + 3; offset += 1) {
      for (const tail of ['😀', '\ud83d', '\ude00', '\ud83d\ud83d', '😀😀', 'é😀x']) {
        for (const text of ['a'.repeat(offset) + tail, 'a'.repeat(offset) + tail + 'zz', '中'.repeat(offset) + tail]) {
          const want = Buffer.byteLength(text);
          expect(both(text), `offset ${offset} tail ${JSON.stringify(tail)}`).toEqual([want, want]);
        }
      }
    }
    // A string made only of pairs, so EVERY chunk boundary lands mid-pair.
    const pairs = '😀'.repeat(3 * CHUNK + 7);
    expect(both(pairs)).toEqual([Buffer.byteLength(pairs), Buffer.byteLength(pairs)]);
    const lonely = '\ud83d'.repeat(2 * CHUNK + 1);
    expect(both(lonely)).toEqual([Buffer.byteLength(lonely), Buffer.byteLength(lonely)]);
  });

  it('agree with Buffer.byteLength on arbitrary strings, lone surrogates included', () => {
    fc.assert(
      fc.property(fc.string({ unit: 'binary', maxLength: 200 }), (text) => {
        const want = Buffer.byteLength(text);
        return utf8ByteLength(text) === want && countUtf8Bytes(text) === want;
      }),
      { numRuns: 2000 },
    );
  });

  it('agree on long arbitrary strings that cross many chunks', () => {
    fc.assert(
      fc.property(
        fc.array(fc.string({ unit: 'binary', minLength: 1, maxLength: 7 }), { minLength: 1, maxLength: 8 }),
        fc.integer({ min: 20_000, max: 70_000 }),
        (pieces, repeats) => {
          const text = pieces.join('').repeat(Math.ceil(repeats / pieces.length));
          const want = Buffer.byteLength(text);
          return utf8ByteLength(text) === want && countUtf8Bytes(text) === want;
        },
      ),
      { numRuns: 40 },
    );
  });
});

describe('TypeScript-specific: unserializable values (not in the fixture)', () => {
  it('a cyclic field is replaced by a marker and every other field is kept', () => {
    const cyclic: Record<string, unknown> = { a: 1 };
    cyclic['self'] = cyclic;
    const result = serializePayload({ nodeId: 'tool:y', durationMs: 1, status: 'ok', output: cyclic });
    expect(result.truncated).toBe(true);
    expect(JSON.parse(result.json)).toEqual({
      nodeId: 'tool:y',
      durationMs: 1,
      status: 'ok',
      output: { __graphmindTruncated: true, bytes: 0, preview: '[unserializable value]' },
      __graphmindTruncated: true,
      fields: ['output'],
    });
  });

  it('a cyclic ARRAY field keeps its type as []', () => {
    const list: unknown[] = [1];
    list.push(list);
    const result = serializePayload({ nodeId: 'n', rows: list });
    expect(JSON.parse(result.json)).toEqual({ nodeId: 'n', rows: [], __graphmindTruncated: true, fields: ['rows'] });
  });

  it('a BigInt field is unserializable in JSON and treated the same way', () => {
    const result = serializePayload({ nodeId: 'n', big: 10n });
    expect(result.truncated).toBe(true);
    expect((result.payload as Record<string, unknown>)['fields']).toEqual(['big']);
  });

  it('an unserializable non-object payload becomes the whole-payload marker', () => {
    const list: unknown[] = [];
    list.push(list);
    const result = serializePayload(list);
    expect(result.payload).toEqual({ __graphmindTruncated: true, bytes: 0, preview: '[unserializable payload]' });
    expect(serializePayload(5n).payload).toEqual({ __graphmindTruncated: true, bytes: 0, preview: '[unserializable payload]' });
  });

  it('undefined serializes as "null" at the top level', () => {
    expect(serializePayload(undefined)).toEqual({ json: 'null', payload: undefined, truncated: false });
  });

  it('an own toJSON is honoured, exactly as JSON.stringify does', () => {
    const payload = { nodeId: 'n', output: { toJSON: () => 'x'.repeat(600 * 1024) } };
    const result = serializePayload(payload);
    expect(result.truncated).toBe(true);
    // Shrunk from the ORIGINAL value (an object whose only key is toJSON).
    expect(utf8ByteLength(result.json)).toBeLessThanOrEqual(MAX_PAYLOAD_BYTES);
    expect(isTruncatedPayload(result.payload)).toBe(true);
  });
});

describe('properties', () => {
  const jsonValue = fc.jsonValue({ maxDepth: 4 });

  it('is idempotent: a result fed back in comes back unchanged', () => {
    fc.assert(
      fc.property(jsonValue, fc.integer({ min: 0, max: 700 * 1024 }), (value, pad) => {
        const payload = { nodeId: 'n', status: 'ok', durationMs: 1, output: value, pad: 'p'.repeat(pad) };
        const once = serializePayload(payload);
        const twice = serializePayload(once.payload);
        return twice.truncated === false && twice.json === once.json && twice.payload === once.payload;
      }),
      { numRuns: 60 },
    );
  });

  it('never exceeds the default budget, and keeps the structural fields when it trims', () => {
    fc.assert(
      fc.property(
        fc.array(fc.tuple(fc.constantFrom('a', 'é', '中', '😀', '\n', '"'), fc.integer({ min: 0, max: 400_000 })), {
          minLength: 1,
          maxLength: 4,
        }),
        (parts) => {
          const payload: Record<string, unknown> = { nodeId: 'tool:t', durationMs: 2, status: 'ok' };
          parts.forEach(([unit, count], i) => {
            payload[`field${'abcd'[i]}`] = unit.repeat(count);
          });
          const result = serializePayload(payload);
          if (utf8ByteLength(result.json) > MAX_PAYLOAD_BYTES) return false;
          if (!result.truncated) return result.payload === payload;
          const out = result.payload as TruncatedPayload & Record<string, unknown>;
          return out.__graphmindTruncated === true && (out['nodeId'] === 'tool:t' || out.fields === undefined);
        },
      ),
      { numRuns: 80 },
    );
  });
});

describe('platform neutrality', () => {
  it('src/shrink.ts uses no Node-only API', () => {
    const source = readFileSync(new URL('../src/shrink.ts', import.meta.url), 'utf8');
    const code = source.replace(/\/\*[\s\S]*?\*\//g, '').replace(/\/\/.*$/gm, '');
    expect(code).not.toMatch(/\bBuffer\b/);
    expect(code).not.toMatch(/from ['"]node:/);
    expect(code).not.toMatch(/\bprocess\./);
    expect(code).not.toMatch(/\brequire\(/);
  });
});
